spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security_tutorial
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update